<?php

function rock_paper_menu() {
    $items = array();
    $items['rock_paper'] = array(
        'title' => 'Rock Paper Scissors',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rock_paper_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['end'] = array(
        'title' => 'Finished',
        'page callback' => 'rock_paper_done',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function rock_paper_form() {
    $form['players'] = array(
        '#title' => 'Player 1, FIGHT',
        '#type' => 'textfield',
        '#description' => t('ROCK, PAPER, OR SCISSORS!?!'),
        '#element_validate' => array('element_validate_input_range'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function rock_paper_form_submit($form, &$form_state) {
        $player1_wins = ["sl", "ls", "dj", "jd", "fk", "kf"];
        $player2_wins = ["jf", "fj", "ks", "sk", "ld", "dl"];
        $draw = ["sj", "js", "dk", "kd", "fl", "lf"];

        $victory_player1 = "Player 1 Wins!!!";
        $victory_player2 = "Player 2 Wins!!!";
        $draw_outcome = "DRAW!!!";

        $input = strtolower($form_state['values']['players']); //change players input to lower case

        if(in_array($input, $player1_wins)) {
            $_SESSION['winner'] = $victory_player1;
        }
        elseif(in_array($input, $player2_wins)) {
            $_SESSION['winner'] = $victory_player2;
        }
        elseif(in_array($input, $draw)) {
            $_SESSION['winner'] = $draw_outcome;
        }

        $form_state['redirect'] = 'end';
    }

function element_validate_input_range($element) {
    if($element['#value'] != ("sl"||"ls"||"dj"||"jd"||"fk"||"kf"||"jf"||"fj"||"ks"||"sk"||"ld"||"dl" ||"sj"||"js"||"dk"||"kd"||"fl"||"lf")) {
    form_error($element, t("Please enter a valid letter combination!"));
    }
}

function rock_paper_done() {
    return $_SESSION['winner'];
}
