<?php

function rock_paper() {
    $items = array();
    $items['rock_paper'] = array(
        'title' => 'Rock Paper Scissors',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rock_paper_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['outcome'] = array(
        'title' => 'Finished',
        'page callback' => 'rock_paper_done',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function rock_paper_form() {
    $form['player_one'] = array(
        '#title' => 'Player 1, FIGHT',
        '#type' => 'textfield',
        '#description' => t('ROCK, PAPER, OR SCISSORS!?!'),
        '#element_validate' => array('element_validate_input_range'),
        '#required' => TRUE,
    );
}

function rock_paper_form_submit($form, &$form_state) {
        $player1_wins = ["sl", "ls", "dj", "jd", "fk", "kf"];
        $player2_wins = ["jf", "fj", "ks", "sk", "ld", "dl"];
        $draw = ["sj", "js", "dk", "kd", "fl", "lf"];

        $victory_player1 = "Player 1 Wins!!!";
        $victory_player2 = "Player 2 Wins!!!";
        $draw_outcome = "DRAW!!!";

        $input = strtolower($input); //change players input to lower case

        if(in_array($input, $player1_wins)) {
            $victory_player1 = $_SESSION['outcome'];
        }
        elseif(in_array($input, $player2_wins)) {
            $victory_player2 = $_SESSION['outcome'];
        }
        elseif(in_array($input, $draw)) {
            $draw_outcome = $_SESSION['outcome'];
        }

    }

function element_validate_input_range($element) {
    if($element['#value'] != "sl", "ls", "dj", "jd", "fk", "kf", "jf", "fj", "ks", "sk", "ld", "dl", "sj", "js", "dk", "kd", "fl", "lf")
    form_error($element, t("Please enter a valid letter combination!"));
}

function rock_paper_done() {
    return $_SESSION['outcome'];
}
